proyecto/aplicacion/urls.py
from django.urls import path

from . import views

app_name = 'aplicacion'
urlpatterns = [
    path('', views.index, name='index') 
]

urlpatterns += [
    path('personas/', views.PersonaListView.as_view(), name='personas'),
    path('comunidades/', views.ComunidadListView.as_view(), name='comunidades'),
    path('actividades/', views.ActividadListView.as_view(), name='actividades'),
    path('actividad/<int:pk>', views.ActividadDetailView.as_view(), name='actividad-detail'),
]

# operaciones persona
urlpatterns += [
    path('persona/create/', views.PersonaCreate.as_view(), name='persona_create'),
    path('persona/<int:pk>/update/', views.PersonaUpdate.as_view(), name='persona_update'),
    path('persona/<int:pk>/delete/', views.PersonaDelete.as_view(), name='persona_delete'),
]

#operaciones comunidad
urlpatterns += [
    path('comunidad/create/', views.ComunidadCreate.as_view(), name='comunidad_create'),
    path('comunidad/<int:pk>/update/', views.ComunidadUpdate.as_view(), name='comunidad_update'),
    path('comunidad/<int:pk>/delete/', views.ComunidadDelete.as_view(), name='comunidad_delete'),
]

#operaciones actividad
urlpatterns += [
    path('actividad/create/', views.ActividadCreate.as_view(), name='actividad_create'),
    path('actividad/<int:pk>/update/', views.ActividadUpdate.as_view(), name='actividad_update'),
    path('actividad/<int:pk>/delete/', views.ActividadDelete.as_view(), name='actividad_delete'),
]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('aplicacion/', include('aplicacion.urls'))
]


urlpatterns +=[
    path('', RedirectView.as_view(url='/aplicacion/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),    
]

proyecto/aplicacion/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date, datetime

# Create your models here.

class Comunidad(models.Model):
    id = models.AutoField(primary_key=True)
    departamento = models.CharField(max_length=200)
    municipio = models.CharField(max_length=200)
    comunidad = models.CharField(max_length=200)

    def __str__(self):
        return self.comunidad

class Persona(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    comunidad = models.ForeignKey(Comunidad, on_delete=models.CASCADE)

    def __str__(self):
        return '%s, %s' % (self.nombre, self.apellido)

    class Meta:
        ordering = ['nombre']

class Actividad(models.Model):
    id = models.AutoField(primary_key=True)
    nombreActividad = models.CharField(max_length=200)
    fecha = models.DateField(null=True, blank=True)
    hora = models.TimeField(null=True, blank=True)
    lugar = models.ForeignKey(Comunidad, on_delete=models.CASCADE)
    conferencista = models.CharField(max_length=200)
    
    def get_absolute_url(self):
        """
        Devuelve el URL a una instancia particular de Persona(update etc)
        """
        return reverse('aplicacion:actividad-detail', args=[str(self.id)])

    def __str__(self):
        return self.nombreActividad

class Participante_Actividad(models.Model):
    actividad = models.ForeignKey(Actividad, on_delete=models.SET_NULL, null=True)
    persona = models.ForeignKey(Persona, on_delete=models.SET_NULL, null=True, verbose_name='Participantes')

proyecto/aplicacion/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from .models import Comunidad, Persona, Actividad, Participante_Actividad
from django.forms import SelectDateWidget
from django.utils import timezone, timesince

class ActividadForm(ModelForm):

    class Meta:

        model = Actividad
        fields = '__all__'
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date'})
        }

class PersonaForm(ModelForm):

    def __init__(self, *args, **kwargs):
            super(PersonaForm, self).__init__(*args, **kwargs)
            for visible in self.visible_fields():
                visible.field.widget.attrs['class'] = 'form-control'
    
    class Meta:
        model = Persona
        fields = '__all__'
        widgets = {
                'nombre': forms.TextInput(attrs={'class': 'input', 'autofocus': True}),
            }

class ComunidadForm(ModelForm):

    def __init__(self, *args, **kwargs):
            super(ComunidadForm, self).__init__(*args, **kwargs)
            for visible in self.visible_fields():
                visible.field.widget.attrs['class'] = 'form-control'
    
    class Meta:
        model = Comunidad
        fields = '__all__'
         
    

class ParticipanteActForm(ModelForm):
    persona = forms.ModelChoiceField(queryset=Persona.objects.all(),empty_label="Seleccione un Participante")

    class Meta:
        model = Participante_Actividad
        exclude = ()

ParticipanteActFormSet = inlineformset_factory(Actividad, Participante_Actividad, form=ParticipanteActForm, extra=5, can_delete=True)

proyecto/aplicacion/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from aplicacion.models import Comunidad, Persona, Actividad, Participante_Actividad
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from aplicacion.forms import PersonaForm
from aplicacion.forms import ComunidadForm
from aplicacion.forms import ActividadForm
from aplicacion.forms import ParticipanteActForm
from aplicacion.forms import ParticipanteActFormSet
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator


def index(request):
    """
    Función vista para la página inicio del sitio.
    """
    # Genera contadores de algunos de los objetos principales
    #num_books = Book.objects.all().count()

    # Renderiza la plantilla HTML index.html con los datos en la variable contexto
    return render(request,'aplicacion/index.html')


class PersonaListView(generic.ListView):
    model = Persona

class ComunidadListView(generic.ListView):
    model = Comunidad

# ------------------------------------

class ActividadListView(generic.ListView):
    model = Actividad

class ActividadDetailView(generic.DetailView):
    model = Actividad

# ------------------------------------
#CLASES CREATE
    
class PersonaCreate(CreateView):
    model = Persona
    # fields = '__all__'
    form_class = PersonaForm
    success_url = reverse_lazy('aplicacion:personas')
    template_name_suffix = '_crear'

class PersonaUpdate(UpdateView):
    model = Persona
    # fields = ['nombre_persona','apellido','edad','comunidad']
    form_class = PersonaForm
    success_url = reverse_lazy('aplicacion:personas')
    template_name_suffix = '_crear'

class PersonaDelete(DeleteView):
    model = Persona
    success_url = reverse_lazy('aplicacion:personas')
    template_name_suffix = '_eliminar'

    @method_decorator(permission_required('aplicacion.delete_persona',reverse_lazy('aplicacion:personas')))
    def dispatch(self, *args, **kwargs):
        return super(PersonaDelete, self).dispatch(*args, **kwargs)
# ------------------------------------

class ComunidadCreate(CreateView):
    model = Comunidad
    # fields = '__all__'
    form_class = ComunidadForm
    success_url = reverse_lazy('aplicacion:comunidades')
    template_name_suffix = '_crear'

class ComunidadUpdate(UpdateView):
    model = Comunidad
    # fields = ['nombre_comunidad','departamento','municipio']
    form_class = ComunidadForm
    success_url = reverse_lazy('aplicacion:comunidades')
    template_name_suffix = '_crear'

class ComunidadDelete(DeleteView):
    model = Comunidad
    success_url = reverse_lazy('aplicacion:comunidades')
    template_name_suffix = '_eliminar'

    @method_decorator(permission_required('aplicacion.delete_actividad',reverse_lazy('aplicacion:comunidades')))
    def dispatch(self, *args, **kwargs):
        return super(ComunidadDelete, self).dispatch(*args, **kwargs)

# ------------------------------------

class ActividadCreate(CreateView):
    model = Actividad
    # fields = '__all__'
    form_class = ActividadForm
    success_url = reverse_lazy('aplicacion:actividades')
    template_name_suffix = '_crear'

    def get_context_data(self, **kwargs):
        context = super(ActividadCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['actividadespar'] = ParticipanteActFormSet(self.request.POST)
        else:
            context['actividadespar'] = ParticipanteActFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        actividadespar = context['actividadespar']
        if actividadespar.is_valid():
            response = super().form_valid(form)
            actividadespar.instance = self.object
            actividadespar.save()
            return response
        else:           
            return super(ActividadCreate, self).form_valid(form)
    
class ActividadUpdate(UpdateView):
    model = Actividad
    fields = '__all__'
    success_url = reverse_lazy('aplicacion:actividades')
    template_name_suffix = '_crear'

    def get_context_data(self, **kwargs):
        context = super(ActividadUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['actividadespar'] = ParticipanteActFormSet(self.request.POST, instance=self.object)
            context['actividadespar'].full_clean()
        else:
            context['actividadespar'] = ParticipanteActFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data(form=form)
        actividadespar = context['actividadespar']
        if actividadespar.is_valid():
            response = super().form_valid(form)
            actividadespar.instance = self.object
            actividadespar.save()
            return response
        else:
            return super(ActividadCreate, self).form_valid(form)

class ActividadDelete(DeleteView):
    model = Actividad
    success_url = reverse_lazy('aplicacion:actividades')
    template_name_suffix = '_eliminar'

    @method_decorator(permission_required('aplicacion.delete_actividad',reverse_lazy('aplicacion:actividades')))
    def dispatch(self, *args, **kwargs):
        return super(ActividadDelete, self).dispatch(*args, **kwargs)

proyecto/aplicacion/templates/aplicacion/actividad_crear.html
{% extends "aplicacion/main_template.html" %}

{% load static %}

{% block title %}<title>Actividades</title>{% endblock %}

{% block content %}

    <div class="section__content section__content--p30">

        <div class="col-md-12">
            <h2>Agregar Actividad</h2> 
            <br>
        </div>              

        <div class="col-lg-6.offset-md-3">
                <div class="card">
                    <div class="card-header">Ingresar datos de Actividad</div>

                    <div class="card-body card-block">
                        <form action="" method="post" class="">
                            <div class="form-group">
                            {% csrf_token %}
                                <table>
                                    {{ form.as_table }}
                                </table>                                                                                       
                            </div>
                    </div>

                            <div class="card-header">Participantes de la Actividad</div>
                                
                                <table class="table">
                                    {{ actividadespar.management_form }}
                    
                                    {% for form in actividadespar.forms %}
                                        {% if forloop.first %}
                                            <thead>
                                            <tr>
                                                {% for field in form.visible_fields %}
                                                    <th>{{ field.label|capfirst }}</th>
                                                {% endfor %}
                                            </tr>
                                            </thead>
                                        {% endif %}
                                            <tr class="formset_row-{{ formset.prefix }}">
                                                {% for field in form.visible_fields %}
                                                    <td>
                                                        {# Include the hidden fields in the form #}
                                                        {% if forloop.first %}
                                                            {% for hidden in form.hidden_fields %}
                                                                {{ hidden }}
                                                            {% endfor %}
                                                        {% endif %}
                                                        {{ field.errors.as_ul }}
                                                        {{ field }}
                                                    </td>
                                                {% endfor %}
                                            </tr>
                                    {% endfor %}
                                </table> 

                            <div class="card-footer">
                                <a href="{% url 'aplicacion:actividades' %}"><button type="button" class="btn btn-dark btn-sm">Cancelar</button></a>
                                <button type="submit" class="btn btn-danger btn-sm pull-right">Agregar</button>
                            </div>
                        </form>
                </div>
        </div>
        
    </div>

    <!-- Scripts necesarios para utilizar el script de la tabla -->
    <script src="{% static 'vendor/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'formset/jquery.formset.js' %}"></script>
    
    <!-- Script para agregar o quitar filas de la tabla Participantes -->
    <script type="text/javascript">
        $('.formset_row-{{ formset.prefix }}').formset({
            addText: 'Agregar',
            deleteText: 'Quitar',
            prefix: '{{ formset.prefix }}',
        });
    </script>

    
   
{% endblock content %}

proyecto/aplicacion/templates/aplicacion/actividad_detail.html
{% extends "aplicacion/main_template.html" %}

{% load static %}

{% block title %}<title>Actividades</title>{% endblock %}

{% block content %}

    <div class="section__content section__content--p30"> 
    
        <div class="col-md-12">
            <h2>Eventos</h2> 
            <br>
        </div>          

        <div class="col-lg-6.offset-md-3">
                <div class="card">
                    <div class="card-header">Eventos a realizarse</div>

                    <div class="card-body card-block">
                            <p><strong>Nombre:</strong> {{ actividad.nombreActividad }}</p>
                            <p><strong>Fecha:</strong> {{ actividad.fecha }}</p>    
                            <p><strong>Hora:</strong> {{ actividad.hora }}</p> 
                            <p><strong>Lugar:</strong> {{ actividad.lugar }}</p>
                            <p><strong>Conferencista:</strong> {{ actividad.conferencista }}</p>
                    </div>
                        
                </div>
        </div> 

        

    </div>

{% endblock content %}

proyecto/aplicacion/templates/aplicacion/actividad_eliminar.html
{% extends "aplicacion/main_template.html" %}

{% load static %}

{% block title %}<title>Eliminar</title>{% endblock %}

{% block content %}

    <div class="section__content section__content--p30">

        <div class="col-md-12">
                <h1>Eliminar</h1> 
                <br>

                <p>Estas seguro que deseas eliminar la Actividad: </p>
                <strong>"{{ actividad }}"</strong>
                <br><br>

                    <form action="" method="POST">
                    {% csrf_token %}          
                    <a href="{% url 'aplicacion:comunidades' %}"><button type="button" class="btn btn-dark btn-sm">Cancelar</button></a> 
                    <button type="submit" class="btn btn-danger btn-sm">Confirmar</button>
                    <br>
                    </form>
        </div>          
   
    </div>
   
{% endblock content %}

proyecto/aplicacion/templates/aplicacion/actividad_list.html
{% extends "aplicacion/main_template.html" %}

{% load static %}

{% block title %}<title>Actividades</title>{% endblock %}

{% block content %}

    <div class="section__content section__content--p30">

        <div class="col-md-12">
                <h1>Nuestras actividades</h1> 
            <a href="{% url 'aplicacion:actividad_create' %}" class="pull-right"><button type="button" class="btn btn-danger">Agregar</button></a>
            <br><br>
        </div>          

        <div class="col-md-12">
            <div class="table-responsive table--no-card m-b-30">
                <table class="table table-borderless table-striped table-earning">

                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Fecha</th>
                            <th>Hora</th>
                            <th>Lugar</th>
                            <th>Conferencista</th>
                            <th style="text-align: center;">Accion</th>

                        </tr>
                    </thead>

                    <tbody>
                        {% if actividad_list %}

                            {% for actividad in actividad_list %}                     
                                <tr>
                                    <td>{{ actividad.nombreActividad }}</td>
                                    <td>{{ actividad.fecha }}</td>
                                    <td>{{ actividad.hora }}</td>
                                    <td>{{ actividad.lugar }}</td>
                                    <td>{{ actividad.conferencista }}</td>
                                    <td style="text-align: center;">
                                        <a href="{% url 'aplicacion:actividad_update' actividad.id %}"><i class="fa fa-edit"></i></a> |
                                        {% if perms.aplicacion.delete_actividad %}
                                        <a href="{% url 'aplicacion:actividad_delete' actividad.id %}"><i class="fa fa-trash"></i></a>
                                        {% endif %}
                                        </td>                                 

                                </tr>
                            {% endfor %}                      
                            
                            {% endif %}   
                    </tbody>
                </table>     
                        
            </div>
        </div>

    </div>
   
{% endblock content %}

proyecto/aplicacion/templates/aplicacion/comunidad_eliminar.html
{% extends "aplicacion/main_template.html" %}

{% load static %}

{% block title %}<title>Comunidades</title>{% endblock %}

{% block content %}

    <div class="section__content section__content--p30">

        <div class="col-md-12">
                <h1>Eliminar un registro</h1> 
                <br>

                <p>¿Deseas eliminar a la Comunidad?: </p>
                <strong>"{{ comunidad }}"</strong>
                <br><br>

                    <form action="" method="POST">
                    {% csrf_token %}          
                    <a href="{% url 'aplicacion:comunidades' %}"><button type="button" class="btn btn-dark btn-sm">Cancelar</button></a> 
                    <button type="submit" class="btn btn-danger btn-sm">Confirmar</button>
                    <br>
                    </form>
        </div>          
   
    </div>
   
{% endblock content %}

proyecto/aplicacion/templates/aplicacion/comunidad_list.html
{% extends "aplicacion/main_template.html" %}

{% load static %}

{% block title %}<title>Comunidades</title>{% endblock %}

{% block content %}

    <div class="section__content section__content--p30">

        <div class="col-md-12">
                <h1>Registros de actividades</h1> 
            <a href="{% url 'aplicacion:comunidad_create' %}" class="pull-right"><button type="button" class="btn btn-danger">Agregar</button></a>
            <br><br>
        </div>          

        <div class="col-md-12">
            <div class="table-responsive table--no-card m-b-30">
                <table class="table table-borderless table-striped table-earning">

                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Departamento</th>
                            <th>Municipio</th>
                            <th style="text-align: center;">Accion</th>

                        </tr>
                    </thead>

                    <tbody>
                        {% if comunidad_list %}

                            {% for comunidad in comunidad_list %}                     
                                <tr>
                                    <td>{{ comunidad.comunidad }}</td>
                                    <td>{{ comunidad.departamento }}</td>
                                    <td>{{ comunidad.municipio }}</td>
                                    <td style="text-align: center;">
                                        <a href="{% url 'aplicacion:comunidad_update' comunidad.id %}"><i class="fa fa-edit"></i></a> |
                                        {% if perms.aplicacion.delete_comunidad %}
                                        <a href="{% url 'aplicacion:comunidad_delete' comunidad.id %}"><i class="fa fa-trash"></i></a>
                                        {% endif %}
                                        </td>                                 

                                </tr>
                            {% endfor %}                      
                            
                            {% endif %}   
                    </tbody>
                </table>     
                        
            </div>
        </div>

    </div>
   
{% endblock content %}

proyecto/aplicacion/templates/aplicacion/main_template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  {% block title %}<title>Comunidad Ebenezer</title> {% endblock %}
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="{% static 'img/eb.jpg' %}" rel="icon">
  <link href="{% static 'img/eb.jpg' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="{% static 'https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800' %}" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
    Theme Name: TheEvent
    Theme URL: https://bootstrapmade.com/theevent-conference-event-bootstrap-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
</head>

<body>

  <!--==========================
    Header
  ============================-->
  <header id="header" class="header-fixed">
    <div class="container">

      <div id="logo" class="pull-left">
        <!-- Uncomment below if you prefer to use a text logo -->
        <!-- <h1><a href="#main">C<span>o</span>nf</a></h1>-->
        <a class="scrollto"><img src="{% static 'img/ebenezer1.png' %}" alt="" title=""></a>
      </div>

      {% block navegar%}
      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-active"><a href="{% url 'aplicacion:index' %}">Home</a></li>


          {% if user.is_anonymous%}
          {% else %}
          <li>
            <a href="#">Comunidades</a>
            <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                <li>
                    <a href="{% url 'aplicacion:comunidad_create' %}">Registrar</a>
                </li>
                <li>
                    <a href="{% url 'aplicacion:comunidades' %}">Listar</a>
                </li>
            </ul>
          </li>
          {% endif %}
          
          {% if user.is_anonymous %}

          {% else %}
          <li>
            <a href="#">Persona</a>
            <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                <li>
                    <a href="{% url 'aplicacion:persona_create' %}">Registrar</a>
                </li>
                <li>
                    <a href="{% url 'aplicacion:personas' %}">Listar</a>
                </li>
            </ul>          
          </li>
          {% endif %}

          {% if user.is_anonymous %}

          {% else %}
          <li>
            <a href="#">Actividades</a>
            <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                <li>
                    <a href="{% url 'aplicacion:actividad_create' %}">Registrar</a>
                </li>
                <li>
                    <a href="{% url 'aplicacion:actividades' %}">Listar</a>
                </li>
            </ul>
          </li>
          {% endif %}

          {% if user.is_authenticated %}
          <li> <a href="#"> User: {{ user.get_username }}</a>
              <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                <li><a href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>   
            </ul>
              {% else %}
              <li><a href="{% url 'login' %}?next={{request.path}}">Login</a></li>   
            {% endif %} 
            </ul>
          </li>
      </nav><!-- #nav-menu-container -->
      {% endblock %}
    </div>
  </header><!-- #header -->

  <main id="main" class="main-page">

    <!--==========================
      Speaker Details Section
    ============================-->
    {% block content%}
    
    {% endblock %}
    

  </main>


  <!--==========================
    Footer
  ============================-->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contáctenos</h4>
            <p>
              Zona 1, Edificio Ebenezer, Ciudad de Guatemala
              <strong>Telefno:</strong> +502 23452523<br>
              <strong>Email:</strong> info@ebenezer.com<br>
            </p>
          </div>
        </div>
      </div>
    </div>

        <div class="container">
          <div class="copyright">
            &copy; Copyright <strong>Ebenezer</strong>. Todos los derechos reservados
          </div>
        </div>
  </footer><!-- #footer -->

  <a href="#" class="back-to-top"><i class="fa fa-angle-up"></i></a>

  <!-- JavaScript Libraries -->
  <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'lib/jquery/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'lib/superfish/hoverIntent.js' %}"></script>
  <script src="{% static 'lib/superfish/superfish.min.js' %}"></script>
  <script src="{% static 'lib/wow/wow.min.js' %}"></script>
  <script src="{% static 'lib/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

  <!-- Contact Form JavaScript File -->
  <script src="{% static 'contactform/contactform.js' %}"></script>

  <!-- Template Main Javascript File -->
  <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

proyecto/aplicacion/templates/aplicacion/persona_list.html
{% extends "aplicacion/main_template.html" %}

{% load static %}

{% block title %}<title>Personas</title>{% endblock %}

{% block content %}

    <div class="section__content section__content--p30">

        <div class="col-md-12">
                <h1>Informacion de personas</h1> 
            <a href="{% url 'aplicacion:persona_create' %}" class="pull-right"><button type="button" class="btn btn-danger">Agregar</button></a>
            <br><br>
        </div>          

        <div class="col-md-12">
            <div class="table-responsive table--no-card m-b-30">
                <table class="table table-borderless table-striped table-earning">

                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Comunidad</th>
                            <th style="text-align: center;">Accion</th>

                        </tr>
                    </thead>

                    <tbody>
                        {% if persona_list %}

                            {% for persona in persona_list %}                     
                                <tr>
                                    <td>{{ persona.nombre }}</td>
                                    <td>{{ persona.apellido }}</td>
                                    <td>{{ persona.comunidad }}</td>
                                    <td style="text-align: center;"> 
                                        <a href="{% url 'aplicacion:persona_update' persona.id %}"><i class="fa fa-edit"></i></a> |
                                        {% if perms.aplicacion.delete_persona %}
                                        <a href="{% url 'aplicacion:persona_delete' persona.id %}"><i class="fa fa-trash"></i> </a>
                                        {% endif %}
                                        </td>                                 

                                </tr>
                            {% endfor %}                      
                            
                            {% endif %}   
                    </tbody>
                </table>     
                        
            </div>
        </div>
    </div>
   
{% endblock content %}